-- 상품 코드별 매출액을 출력하시오
# SELECT PRODUCT_ID,SALES_AMOUNT
# FROM OFFLINE_SALE
# GROUP BY PRODUCT_ID
SELECT P.PRODUCT_CODE ,SUM(SALES_AMOUNT)*P.PRICE AS SALES
FROM OFFLINE_SALE O
JOIN PRODUCT P
ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC